name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .github/workflows/main.yaml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: continuedev/continue-publish-action@v1.0.10
        with:
          api-key: con-34fd5be0aec2706adb92a9f9a525e95d0d53e2c717bae546bdac09ae6d93932b
          owner-slug: nate-sesti
          paths: packages/**
          continue-api-domain: api-test.continue.dev
