name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - blocks/public/**
      - assistants/public/**
      - .github/workflows/main.yaml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # continuedev blocks
      - uses: continuedev/continue-publish-action@v1
        with:
          api-key: ${{ secrets.CONTINUE_API_KEY }}
          owner-slug: continuedev
          paths: blocks/public/continuedev/**

      # Starter blocks
      - uses: continuedev/continue-publish-action@v1
        with:
          api-key: ${{ secrets.CONTINUE_API_KEY }}
          owner-slug: starter
          paths: blocks/public/starter/**

      # Starter assistants
      - uses: continuedev/continue-publish-action@v1
        with:
          api-key: ${{ secrets.CONTINUE_API_KEY }}
          owner-slug: starter
          is-assistant: true
          paths: assistants/public/starter/**

      # continuedev assistants
      # - uses: continuedev/continue-publish-action@v1
      #   with:
      #     owner-slug: continuedev
      #     paths: assistants/public/**
      #     is-assistant: true
      #     api-key: ${{ secrets.CONTINUE_API_KEY }}
