name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .github/workflows/main.yaml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: continuedev/continue-publish-action@v1
        with:
          api-key: ${{ secrets.CONTINUE_API_KEY }}
          owner-slug: continuedev
          paths: blocks/public/continuedev/**

      - uses: continuedev/continue-publish-action@v1
        with:
          api-key: ${{ secrets.CONTINUE_API_KEY }}
          owner-slug: starter
          paths: blocks/public/starter/**

  publish-official:
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        owner: [openai, anthropic, google, mistral, deepseek]
    steps:
      - uses: actions/checkout@v4

      - uses: continuedev/continue-publish-action@v1
        with:
          api-key: ${{ secrets.CONTINUE_API_KEY }}
          owner-slug: ${{ matrix.owner }}
          paths: blocks/public/official/${{ matrix.owner }}/**
