name: Publish Package

on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - .github/workflows/main.yaml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: continuedev/continue-publish-action@v1.0.7
        with:
          api-key: ${{ secrets.TEST_CONTINUE_API_KEY }}
          owner-slug: nate-sesti
          paths: packages/**
          continue-api-domain: api-test.continue.dev
